-- Plan Items 3/7: policy-routed material deltas, digests, and delivery audit.

CREATE TABLE IF NOT EXISTS public.finding_alert_policies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE CHECK (btrim(name) <> ''),
    finding_type TEXT CHECK (finding_type IS NULL OR finding_type IN (
        'credential_exposure', 'infrastructure_cluster', 'cross_bot_pattern'
    )),
    min_priority SMALLINT NOT NULL DEFAULT 1 CHECK (min_priority BETWEEN 1 AND 10),
    monitored_entity_type TEXT CHECK (
        monitored_entity_type IS NULL OR monitored_entity_type IN (
            'credential', 'bot', 'webhook_host', 'domain', 'url',
            'wallet', 'media_hash', 'user_pseudonym'
        )
    ),
    monitored_entity_value TEXT,
    cadence TEXT NOT NULL CHECK (cadence IN ('immediate', 'daily', 'weekly')),
    channel TEXT NOT NULL CHECK (channel IN ('telegram', 'webhook')),
    timezone TEXT NOT NULL DEFAULT 'UTC' CHECK (btrim(timezone) <> ''),
    quiet_start TIME,
    quiet_end TIME,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_by UUID DEFAULT auth.uid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT finding_alert_policy_entity_pair CHECK (
        (monitored_entity_type IS NULL AND monitored_entity_value IS NULL)
        OR (
            monitored_entity_type IS NOT NULL
            AND btrim(COALESCE(monitored_entity_value, '')) <> ''
        )
    ),
    CONSTRAINT finding_alert_policy_quiet_pair CHECK (
        (quiet_start IS NULL) = (quiet_end IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_finding_alert_policies_route
    ON public.finding_alert_policies(enabled, cadence, channel, min_priority);

CREATE TABLE IF NOT EXISTS public.finding_alert_deliveries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    policy_id UUID NOT NULL REFERENCES public.finding_alert_policies(id) ON DELETE RESTRICT,
    finding_id UUID NOT NULL REFERENCES public.findings(id) ON DELETE CASCADE,
    material_version INTEGER NOT NULL CHECK (material_version >= 1),
    cadence TEXT NOT NULL CHECK (cadence IN ('immediate', 'daily', 'weekly')),
    channel TEXT NOT NULL CHECK (channel IN ('telegram', 'webhook')),
    status TEXT NOT NULL CHECK (status IN ('pending', 'deferred', 'delivered', 'failed')),
    reason TEXT NOT NULL CHECK (btrim(reason) <> ''),
    payload_redacted JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(payload_redacted) = 'object'),
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    claim_until TIMESTAMPTZ,
    first_evaluated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_evaluated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    delivered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT finding_alert_delivery_once UNIQUE (
        policy_id, finding_id, material_version
    )
);

CREATE INDEX IF NOT EXISTS idx_finding_alert_deliveries_status
    ON public.finding_alert_deliveries(status, last_evaluated_at DESC);
CREATE INDEX IF NOT EXISTS idx_finding_alert_deliveries_finding
    ON public.finding_alert_deliveries(finding_id, material_version DESC);

CREATE TABLE IF NOT EXISTS public.finding_alert_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id UUID NOT NULL
        REFERENCES public.finding_alert_deliveries(id) ON DELETE CASCADE,
    policy_id UUID NOT NULL,
    finding_id UUID NOT NULL,
    material_version INTEGER NOT NULL,
    status TEXT NOT NULL,
    reason TEXT NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_finding_alert_audit_recorded
    ON public.finding_alert_audit(recorded_at DESC, status);

CREATE OR REPLACE FUNCTION public.set_finding_alert_policy_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $function$
BEGIN
    NEW.updated_at := NOW();
    RETURN NEW;
END
$function$;

DROP TRIGGER IF EXISTS finding_alert_policy_updated_at
    ON public.finding_alert_policies;
CREATE TRIGGER finding_alert_policy_updated_at
BEFORE UPDATE ON public.finding_alert_policies
FOR EACH ROW EXECUTE FUNCTION public.set_finding_alert_policy_updated_at();

CREATE OR REPLACE FUNCTION public.audit_finding_alert_delivery()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = ''
AS $function$
BEGIN
    IF TG_OP = 'INSERT'
       OR ROW(NEW.status, NEW.reason) IS DISTINCT FROM ROW(OLD.status, OLD.reason)
    THEN
        INSERT INTO public.finding_alert_audit (
            delivery_id, policy_id, finding_id, material_version, status, reason
        ) VALUES (
            NEW.id, NEW.policy_id, NEW.finding_id,
            NEW.material_version, NEW.status, NEW.reason
        );
    END IF;
    RETURN NEW;
END
$function$;

DROP TRIGGER IF EXISTS finding_alert_delivery_audit
    ON public.finding_alert_deliveries;
CREATE TRIGGER finding_alert_delivery_audit
AFTER INSERT OR UPDATE ON public.finding_alert_deliveries
FOR EACH ROW EXECUTE FUNCTION public.audit_finding_alert_delivery();

CREATE OR REPLACE FUNCTION public.claim_finding_alert(
    p_policy_id UUID,
    p_finding_id UUID,
    p_material_version INTEGER,
    p_cadence TEXT,
    p_channel TEXT,
    p_payload_redacted JSONB,
    p_evaluated_at TIMESTAMPTZ
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE
    delivery_uuid UUID;
BEGIN
    INSERT INTO public.finding_alert_deliveries (
        policy_id, finding_id, material_version, cadence, channel,
        status, reason, payload_redacted, attempt_count, claim_until,
        first_evaluated_at, last_evaluated_at
    ) VALUES (
        p_policy_id, p_finding_id, p_material_version, p_cadence, p_channel,
        'pending', 'claimed', COALESCE(p_payload_redacted, '{}'::jsonb), 1,
        p_evaluated_at + INTERVAL '10 minutes', p_evaluated_at, p_evaluated_at
    )
    ON CONFLICT (policy_id, finding_id, material_version) DO UPDATE SET
        cadence = EXCLUDED.cadence,
        channel = EXCLUDED.channel,
        status = 'pending',
        reason = 'reclaimed',
        payload_redacted = EXCLUDED.payload_redacted,
        attempt_count = public.finding_alert_deliveries.attempt_count + 1,
        claim_until = EXCLUDED.claim_until,
        last_evaluated_at = EXCLUDED.last_evaluated_at,
        updated_at = NOW()
    WHERE public.finding_alert_deliveries.status IN ('deferred', 'failed')
       OR (
            public.finding_alert_deliveries.status = 'pending'
            AND public.finding_alert_deliveries.claim_until < p_evaluated_at
       )
    RETURNING id INTO delivery_uuid;

    RETURN delivery_uuid;
END
$function$;

CREATE OR REPLACE FUNCTION public.defer_finding_alert(
    p_policy_id UUID,
    p_finding_id UUID,
    p_material_version INTEGER,
    p_cadence TEXT,
    p_channel TEXT,
    p_reason TEXT,
    p_payload_redacted JSONB,
    p_evaluated_at TIMESTAMPTZ
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
DECLARE
    delivery_uuid UUID;
BEGIN
    INSERT INTO public.finding_alert_deliveries (
        policy_id, finding_id, material_version, cadence, channel,
        status, reason, payload_redacted, first_evaluated_at, last_evaluated_at
    ) VALUES (
        p_policy_id, p_finding_id, p_material_version, p_cadence, p_channel,
        'deferred', p_reason, COALESCE(p_payload_redacted, '{}'::jsonb),
        p_evaluated_at, p_evaluated_at
    )
    ON CONFLICT (policy_id, finding_id, material_version) DO UPDATE SET
        status = 'deferred',
        reason = EXCLUDED.reason,
        payload_redacted = EXCLUDED.payload_redacted,
        last_evaluated_at = EXCLUDED.last_evaluated_at,
        updated_at = NOW()
    WHERE public.finding_alert_deliveries.status <> 'delivered'
      AND (
            public.finding_alert_deliveries.status <> 'pending'
            OR public.finding_alert_deliveries.claim_until < p_evaluated_at
      )
    RETURNING id INTO delivery_uuid;

    RETURN delivery_uuid;
END
$function$;

CREATE OR REPLACE FUNCTION public.complete_finding_alert(
    p_delivery_id UUID,
    p_success BOOLEAN,
    p_reason TEXT,
    p_completed_at TIMESTAMPTZ
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $function$
BEGIN
    UPDATE public.finding_alert_deliveries
    SET status = CASE WHEN p_success THEN 'delivered' ELSE 'failed' END,
        reason = p_reason,
        claim_until = NULL,
        delivered_at = CASE WHEN p_success THEN p_completed_at ELSE NULL END,
        last_evaluated_at = p_completed_at,
        updated_at = NOW()
    WHERE id = p_delivery_id
      AND status = 'pending';
    RETURN FOUND;
END
$function$;

-- Default behavior: only high-priority material deltas alert immediately;
-- the separate daily policy produces a bounded Top Findings digest.
INSERT INTO public.finding_alert_policies (
    id, name, min_priority, cadence, channel, timezone, quiet_start, quiet_end
) VALUES
    (
        '10000000-0000-0000-0000-000000000001',
        'Default high-priority material deltas',
        8, 'immediate', 'telegram', 'UTC', '22:00', '07:00'
    ),
    (
        '10000000-0000-0000-0000-000000000002',
        'Daily Top Findings',
        1, 'daily', 'telegram', 'UTC', NULL, NULL
    )
ON CONFLICT DO NOTHING;

ALTER TABLE public.finding_alert_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finding_alert_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finding_alert_audit ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS finding_alert_policies_authenticated_read
    ON public.finding_alert_policies;
CREATE POLICY finding_alert_policies_authenticated_read
    ON public.finding_alert_policies FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS finding_alert_deliveries_authenticated_read
    ON public.finding_alert_deliveries;
CREATE POLICY finding_alert_deliveries_authenticated_read
    ON public.finding_alert_deliveries FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS finding_alert_audit_authenticated_read
    ON public.finding_alert_audit;
CREATE POLICY finding_alert_audit_authenticated_read
    ON public.finding_alert_audit FOR SELECT TO authenticated USING (true);

REVOKE ALL ON public.finding_alert_policies FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.finding_alert_deliveries FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.finding_alert_audit FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.finding_alert_policies TO authenticated;
GRANT SELECT ON public.finding_alert_deliveries TO authenticated;
GRANT SELECT ON public.finding_alert_audit TO authenticated;
GRANT ALL ON public.finding_alert_policies TO service_role;
GRANT ALL ON public.finding_alert_deliveries TO service_role;
GRANT ALL ON public.finding_alert_audit TO service_role;

REVOKE ALL ON FUNCTION public.claim_finding_alert(
    UUID, UUID, INTEGER, TEXT, TEXT, JSONB, TIMESTAMPTZ
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_finding_alert(
    UUID, UUID, INTEGER, TEXT, TEXT, JSONB, TIMESTAMPTZ
) TO service_role;
REVOKE ALL ON FUNCTION public.defer_finding_alert(
    UUID, UUID, INTEGER, TEXT, TEXT, TEXT, JSONB, TIMESTAMPTZ
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.defer_finding_alert(
    UUID, UUID, INTEGER, TEXT, TEXT, TEXT, JSONB, TIMESTAMPTZ
) TO service_role;
REVOKE ALL ON FUNCTION public.complete_finding_alert(
    UUID, BOOLEAN, TEXT, TIMESTAMPTZ
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.complete_finding_alert(
    UUID, BOOLEAN, TEXT, TIMESTAMPTZ
) TO service_role;

COMMENT ON TABLE public.finding_alert_policies IS
    'Operator alert routing by finding type, priority, entity, cadence, channel, timezone, and quiet hours.';
COMMENT ON TABLE public.finding_alert_deliveries IS
    'Idempotent claim/delivery state for each policy and material finding version.';
COMMENT ON TABLE public.finding_alert_audit IS
    'Append-only status transitions used for weekly alert coverage and suppression review.';
